name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install System Dependencies
      run: |
        brew install exiftool

    - name: Run Unit Tests
      run: |
        python3 -m unittest discover -s tests -v
